[build.environment]
  NODE_VERSION = "20.12.0"
  NPM_CONFIG_FUND = "false"
  NPM_CONFIG_AUDIT = "false"

[build]
  command = "rm -rf node_modules package-lock.json && npm cache clean --force && npm install && npm run build"
  publish = "dist"